// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  banner_second: dynamic(() => import("./BannerSecond")),
  body: dynamic(() => import("./Body")),
  breadcrumbs: dynamic(() => import("./Breadcrumbs")),
  col_three_cards: dynamic(() => import("./ColThreeCards")),
  hero: dynamic(() => import("./Hero")),
  testimonials: dynamic(() => import("./Testimonials")),
};
